### ISSUE TITLE
Edge classification of heterogeneous graphs

### ISSUE THREAD

**Issue by yzc1103** [graphdeeplearning/benchmarking-gnns#11] opened 2020-04-09 08:07 UTC
Can you give me some suggestion about how to build a heterogeneous graph with node features and edge features and do edge classification? Thank you very much!

**Comment by chaitjo** [comment] 2020-04-10 16:19
Maybe you can provide more information about your data domain/requirements? 

In general, you can look at the dataset TSP. In TSP, the task is edge classification (binary) and the data format is:
- Node features are 2D vectors representing the coordinates, which are embedded to d-dimension using Linear projections. For heterogenous graphs with categorical features, you can use embeddings/one-hot features instead.
- Edge features are single values representing edge distances, which are again embedded with Linear projections. It is simple to extend this to vector features on edges or categorical features (and use embedding, in case of categoricals).

**Comment by yzc1103** [comment] 2020-04-11 08:45
Thank you very much for your reply, but I have a question. The type of each node in the TSP dataset is the same, but if there are two node types in the dataset, how to change the homogeneous network classification model into a heterogeneous network such as GatedGCNNet?
Looking forward to your reply again. Thank you very much~

**Comment by chaitjo** [comment] 2020-04-11 14:13
Here's how I'd approach having multiple types of nodes, for e.g., molecule graphs can have several types of nodes for each atom in the periodic table. I would assign numerical integer values to each type. Then, in my model, the node input layer would be an Embedding lookup table, exactly as in this model for molecule tasks: https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/nets/molecules_graph_regression/gcn_net.py#L32

You can give the same treatment to heterogenous edge types, too. Catgorical integer values --> Embedding lookup --> GNN layers. Hope that helps.

**Comment by chaitjo** [comment] 2020-04-16 01:28
Closing due to lack of follow up.

**Closed by chaitjo** 2020-04-16 01:28 UTC
